[package]
org = "ballerina"
name = "ftp"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["FTP", "SFTP", "remote file", "file transfer", "client", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-ftp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
path = "./lib/commons-vfs2-@commons.vfs2.version@.jar"

[[platform.java11.dependency]]
path = "./lib/jsch-@jsch.version@.jar"

[[platform.java11.dependency]]
path = "./lib/commons-net-@commons.net.version@.jar"

[[platform.java11.dependency]]
path = "./lib/testng-@testng.version@.jar"

[[platform.java11.dependency]]
path = "./lib/MockFtpServer-@mockftpserver.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/sshd-core-@sshd.core.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftpserver-core-@ftpserver.core.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ftplet-api-@ftplet.api.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/mina-core-@mina.core.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/aopalliance-@aopalliance.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/jcl-over-slf4j-@jcl.slf4j.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ftp-native"
version = "@toml.version@"
path = "../native/build/libs/ftp-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/ftp-test-utils-@project.version@.jar"
scope = "testOnly"
